브로드 캐스팅

- 두 배열의 차원의 크기가 같다 -> 그냥 계산
- 두 배열의 차원이 다르고 한 배열의 차원이 1차원(벡터)
- 차원을 늘렸을 때 계산이 가능한 경우!**

# 난수 생성 함수

In [ ]:
import numpy as np

In [ ]:
a = np.random.rand(2,2) # 0~1 사이에 값 랜덤
print(a)

[[0.4005604  0.63533585]
 [0.3403159  0.95083351]]


In [ ]:
b = np.random.randn(2,2) #평균이 0, 분산이 1: 표준 정규 분포
print(b)

[[ 1.22980499  1.87067131]
 [-1.34558468  0.98043874]]


In [ ]:
c = np.random.randint(0,10,size=5)
print(c)

[3 1 1 5 9]


In [ ]:
c2 = np.random.randint(0,10,size=(2,2))
print(c2)

[[1 9]
 [0 3]]


In [ ]:
d = np.arange(10) # 0~9까지
np.random.shuffle(d) # 복사본 생성이 x, 원본 값이 변한다.
print(d)

[8 5 2 4 6 3 9 7 1 0]


In [ ]:
choice = np.random.choice(d,5) # 중복이 허용
print(choice)

[5 4 6 4 4]


In [ ]:
choice = np.random.choice(d,5,replace=False) # 중복이 허용 x
print(choice)

[7 9 4 2 3]


In [ ]:
choice = np.random.choice(d,5,p=[0.1, 0, 0.3, 0.2, 0.4, 0, 0, 0, 0, 0]) # 중복이 허용 x
print(choice) # 지정확률

[6 2 2 2 4]


In [ ]:
# permutation 순열
a = np.arange(10)
a_p = np.random.permutation(a)

print(a_p)
print(a)

[2 1 7 8 3 4 5 0 6 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 정규분포를 따르는 난수 생성
# a = np.random.normal('평균', '표준편차', '갯수')
a = np.random.normal(0,1,3)
print(a)

[-0.8693275   0.5428389  -1.13598067]


# pandas

- 데이터 자체를 분석, 파악
- 표
- 데이터 다루는 데 초점
- 정렬, 필터링, 그룹화, 집계

- 데이터 로딩 및 저장
- 데이터 인덱싱 및 슬라이싱
- 결측치 처리
- 데이터 변환
- 데이터 집계 및 그룹화
-----
- 시계열 데이터
- 데이터 시각화


## 1. series(시리즈)
- 인덱스를 지정할 수 있음

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([1,2,3,4])
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [ ]:
s2 = pd.Series({'a': 1, 'b' : 2, 'c' : 3, 'd' : 4})
print(s2)

a    1
b    2
c    3
d    4
dtype: int64


In [ ]:
s3 = pd.Series(5, index=[0,1,2])
print(s3)

0    5
1    5
2    5
dtype: int64


In [ ]:
data = [1,2,3,4,5]
index = ['a','b','c','d','e']
series = pd.Series(data, index=index) #활용
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
s[::-1]

4    5
3    4
2    3
1    2
0    1
dtype: int64

In [ ]:
s[:-1]

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
s[:4]

0    1
1    2
2    3
3    4
dtype: int64

## Boolean indexing

In [ ]:
print(s > 2)

0    False
1    False
2     True
3     True
4     True
dtype: bool


In [ ]:
print(s[s>2])

2    3
3    4
4    5
dtype: int64


In [ ]:
print(s[s<5])

0    1
1    2
2    3
3    4
dtype: int64


In [ ]:
print(s + 100)
print(s - 100)
print(s * 100)
print(s ** 100)
print(s / 100)
print(s % 100)
print(s // 100)

0    101
1    102
2    103
3    104
4    105
dtype: int64
0   -99
1   -98
2   -97
3   -96
4   -95
dtype: int64
0    100
1    200
2    300
3    400
4    500
dtype: int64
0                      1
1                      0
2   -2984622845537545263
3                      0
4   -3842938066129721103
dtype: int64
0    0.01
1    0.02
2    0.03
3    0.04
4    0.05
dtype: float64
0    1
1    2
2    3
3    4
4    5
dtype: int64
0    0
1    0
2    0
3    0
4    0
dtype: int64


## series 객체에 접근

In [ ]:
print(s.keys)
print(s.values)

<bound method Series.keys of 0    1
1    2
2    3
3    4
4    5
dtype: int64>
[1 2 3 4 5]


In [ ]:
s2 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})
print(s2.keys)

<bound method Series.keys of a    1
b    2
c    3
d    4
dtype: int64>


In [ ]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
# items

print(s2.items()) # zip ->  순회가 가능, 쌍

In [ ]:
for a, b in s2.items():
    print(f'인덱스: {a}, 데이터: {b}')

인덱스: a, 데이터: 1
인덱스: b, 데이터: 2
인덱스: c, 데이터: 3
인덱스: d, 데이터: 4


In [ ]:
s = pd.Series([10,20,30,40], index=['a','b','c','d'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64


In [ ]:
print(s.loc['b']) # 행에 접근
print(s.loc['b':'d'])

20
b    20
c    30
d    40
dtype: int64


In [ ]:
print(s.iloc[1]) #(행에 기반한) 열에 접근

20


In [ ]:
print(s.at['a']) # loc과 비슷, 하나의 값만 가져올 때

10


In [ ]:
print(s.iat[0]) # at에 기반

10


In [ ]:
print(s.get('e'))  # 없을 때 값 처리 방법이 다름, error가 나지 않고 없다는 걸 알려줌

None


In [ ]:
print(s.get('e', default=-1)) # 없을 때 값 처리 방법이 다름, error가 나지 않고 없다는 걸 알려줌

-1


## 결측값 (Nan, None)

- isna()
- isnull()

Nan(Not a number) -> float
None -> none 

In [ ]:
data = [1,2,3,None]
print(pd.Series(data))

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64


In [ ]:
data = [1,2,3,None]

s = pd.Series(data)

print(s.isna())
print(s.isnull())

0    False
1    False
2    False
3     True
dtype: bool
0    False
1    False
2    False
3     True
dtype: bool


In [ ]:
print(s.isna().sum())


1


결측치 제거

In [ ]:
s.dropna()

0    1.0
1    2.0
2    3.0
dtype: float64

결측치를 0을 치환

In [ ]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [ ]:
s.fillna(0)

0    1.0
1    2.0
2    3.0
3    0.0
dtype: float64

## series함수

In [ ]:
s = pd.Series([1,3,5,7,9])

In [ ]:
s.count() # 카운트 함수

5

In [ ]:
s.min() # 최소값

1

In [ ]:
s.max()

9

In [ ]:
s.max()

9

In [ ]:
print(s.mean())
print(s.median())
print(s.std())
print(s.var())

5.0
5.0
3.1622776601683795
10.0


In [ ]:
s.describe() # 기초통계내용

count    5.000000
mean     5.000000
std      3.162278
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64