In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4]) #1차원 배열 생성

In [3]:
print(a)

[1 2 3 4]


In [4]:
l = [1, 2, 3, 4]
print(l)

[1, 2, 3, 4]


In [5]:
print(a.shape) # 4행 0열(튜플)

(4,)


In [6]:
print(a.ndim)

1


In [7]:
print(a.dtype) # 배열의 데이터 타입

int64


In [8]:
print(a.itemsize) # 각 요소의 바이트 단위 크기

8


In [9]:
b = np.array([[1, 2], [3,4]])
print(b)

[[1 2]
 [3 4]]


In [10]:
print(b)
print(b.ndim)
print(b.dtype)
print(b.dtype)
print(b.nbytes)

[[1 2]
 [3 4]]
2
int64
int64
32


In [11]:
c = np.array([[[1, 2], [3,4]], [[5, 6],[7, 8]]])

print(c)
print(c.ndim)
print(c.dtype)
print(c.dtype)
print(c.nbytes)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
int64
int64
64


In [12]:
#하나의 숫자값: 스칼라

s = np.array(1)
print(s)

1


In [ ]:
# 1차원 : 백터 
# 2차원 : 행렬(matrix) 
# 3차원 : 텐서(tensor) 

In [15]:
# for 문을 이용해서 베영 생성

f = np.array([i for i in range(0, 10, 2)])

print(f)
print(f.ndim)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)

[0 2 4 6 8]
1
int64
8
40


In [16]:
data = [1.1, 2, 3]

i = np.array(data, dtype=np.int32)
print(i)

[1 2 3]


In [17]:
print(i.dtype)

int32


In [18]:
data2 = [-1, 2, 3]

ui = np.array(data2, dtype=np.uint32)
print(ui)

[4294967295          2          3]


In [22]:
c = np.array([1 + 2j, 3 + 2j, 5 + 2j], dtype=np.complex64)

In [23]:
print(c.real) # 실수
print(c.imag) # 허수


[1. 3. 5.]
[2. 2. 2.]


In [24]:
data = [1, 2, 3]

s = np.string_(data)
print(s)

b'\x01\x02\x03'


In [25]:
print(s.dtype)

|S3


In [28]:
data3 = [1, 2, 3, 4, 5]

s2 = np.string_(data3)
print(s2)
print(s2.dtype)

b'\x01\x02\x03\x04\x05'
|S5


In [29]:
u = np.array(data3, dtype='U')

print(u)
print(u.dtype)


['1' '2' '3' '4' '5']
<U1


In [30]:
l1 = np.array([True, False, True])
l2 = np.array([False, True, False])

In [31]:
data = [1.1, 2, 3]

a = np.float64(data)
print(a)
print(a.dtype) 

[1.1 2.  3. ]
float64


In [32]:
a = a.astype(np.int64)

print(a)
print(a.dtype) 

[1 2 3]
int64


In [33]:
b = np.uint16(0)

print(b)
print(b.dtype) 

0
uint16


In [34]:
b = b - 1

In [35]:
print(b)
print(b.dtype) 

-1
int64


In [36]:
import time

data =[[1,2,3], [4,5,6]]
data2 =[[1,1,1], [2,2,2], [3,3,3]]

start_time = time.time()

for i in range(len(data)):
    for j in range(len(data[0])):

In [38]:
d = np.array([0, np.pi/2, np.pi])

sin_ = np.sin(d)
cos_ = np.cos(d)
tan_ = np.tan(d)

print(sin_)
print(cos_)
print(tan_)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [39]:
print('a' + 'b')

ab


In [40]:
x = [1, 2, 3]
y = [4, 5, 6]

In [41]:
concat = np.concatenate([x,y])
print(concat)

[1 2 3 4 5 6]


In [43]:
x2 = [[1,2], [3,4]]
y2 = [[4,5], [6,7]]

concat2 = np.concatenate([x2,y2], axis=1)
concat3 = np.concatenate([x2,y2], axis=0)
print(concat2)
print(concat3)

[[1 2 4 5]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [44]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
h = np.hstack([x2, y2])
print(h)

[[1 2 4 5]
 [3 4 6 7]]


In [47]:
v = np.vstack([x2, y2])
print(v)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [49]:
x2 = np.array([[1,2], [3,4], [5,6]])

h2 = np.hsplit(x2, 2)

h2

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]])]

In [51]:
v2 = np.vsplit(x2, 3)

v2

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

In [52]:
zero = np.zeros([3,4])

In [56]:
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [54]:
one = np.ones([3,4])

one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
eye = np.eye(3)

eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
arr1 = np.array([-1,-2,-3,-4])
abs_arr = np.abs(arr1)

print(abs_arr)

[1 2 3 4]


In [58]:
arr2 = np.array([1,4,9,16])
sqrt_arr = np.sqrt(arr2)

print(sqrt_arr)

[1. 2. 3. 4.]


In [59]:
a = np.array([1,2,3,4,5])
a_mean = np.mean(a)

print(a_mean)

3.0


In [60]:
b = np.array([1,3,5,7,9])
b_median = np.median(b)

print(b_median)

5.0


In [61]:
c = np.array([1,2,3,4,5])
c_std = np.std(c)

print(c_std)

1.4142135623730951


In [62]:
d = np.array([1,2,3,4,5])
d_var = np.var(d)

print(d_var)

2.0


In [64]:
d = np.array([1,2,3,4,5])
d_sum = np.sum(d)

print(d_sum)

15


In [65]:
d_cumsum = np.cumsum(d)
print(d_cumsum)

[ 1  3  6 10 15]


In [66]:
min = np.argmin(d)
print(min)

0


In [68]:
max = np.argmax(d)
print(max)

4


In [69]:
a = np.array([0,0,0,1])

a_true = np.any(a)
print(a_true)

True


In [70]:
a_all = np.all(a)

print(a_all)

False


In [74]:
a = np.array([1,2,np.nan,4])
a_nsum = np.nansum(a)
print(a_nsum)

7.0


In [75]:
a_sum = np.sum(a)
print(a_sum)

nan


In [78]:
d = np.array([1,2,3,4,5])
condition = np.where(d<3, d, 0)
condition1 = np.where(d<3)
print(condition)
print(condition1)

[1 2 0 0 0]
(array([0, 1]),)


In [81]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

even_a = a[a % 2 ==0]

print(even_a)
print(a)

[ 2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [82]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a + b
print(c)

[5 7 9]


In [87]:
d = np.array([[1],[2],[3]])
e = np.array([4,5,6])

f = d + e

print(f)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


- 두 배열의 차원 수가 다를 경우, 더 작은 차원의 배열에 큰 차원의 배열이 맞을 때까지 1을 추가한다.

- 두 배열의 차원 수가 같을 경우에도, 크기가 1인 차원이 있다면 다른 배열의 크기와 일치하도록 복제된다.

- 두 배열의 차원 수가 같을 경우에도, 모든 